# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 586)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(76, 76, 76);\n"
"font: italic 9pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(27, 27, 27);\n"
"border: 10px")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 354, 491))
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lightLabel = QtWidgets.QLabel(self.page)
        self.lightLabel.setMinimumSize(QtCore.QSize(40, 40))
        self.lightLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.lightLabel.setStyleSheet("color: rgb(208, 208, 208);")
        self.lightLabel.setObjectName("lightLabel")
        self.verticalLayout.addWidget(self.lightLabel)
        self.lightRadioButton = QtWidgets.QLabel(self.page)
        self.lightRadioButton.setMinimumSize(QtCore.QSize(30, 20))
        self.lightRadioButton.setMaximumSize(QtCore.QSize(30, 20))
        self.lightRadioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.lightRadioButton.setObjectName("lightRadioButton")
        self.verticalLayout.addWidget(self.lightRadioButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doorLable = QtWidgets.QLabel(self.page)
        self.doorLable.setMinimumSize(QtCore.QSize(40, 40))
        self.doorLable.setMaximumSize(QtCore.QSize(40, 40))
        self.doorLable.setStyleSheet("color: rgb(208, 208, 208);")
        self.doorLable.setObjectName("doorLable")
        self.verticalLayout_2.addWidget(self.doorLable)
        self.doorRadioButton = QtWidgets.QLabel(self.page)
        self.doorRadioButton.setMinimumSize(QtCore.QSize(30, 20))
        self.doorRadioButton.setMaximumSize(QtCore.QSize(30, 20))
        self.doorRadioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.doorRadioButton.setObjectName("doorRadioButton")
        self.verticalLayout_2.addWidget(self.doorRadioButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.airConditionerLable = QtWidgets.QLabel(self.page)
        self.airConditionerLable.setMinimumSize(QtCore.QSize(40, 40))
        self.airConditionerLable.setMaximumSize(QtCore.QSize(40, 40))
        self.airConditionerLable.setStyleSheet("color: rgb(208, 208, 208);")
        self.airConditionerLable.setObjectName("airConditionerLable")
        self.verticalLayout_3.addWidget(self.airConditionerLable)
        self.airConditionerRadioButton = QtWidgets.QLabel(self.page)
        self.airConditionerRadioButton.setMinimumSize(QtCore.QSize(30, 20))
        self.airConditionerRadioButton.setMaximumSize(QtCore.QSize(30, 20))
        self.airConditionerRadioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.airConditionerRadioButton.setObjectName("airConditionerRadioButton")
        self.verticalLayout_3.addWidget(self.airConditionerRadioButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.feedBackBrowser = QtWidgets.QTextBrowser(self.page)
        self.feedBackBrowser.setMaximumSize(QtCore.QSize(16777215, 40))
        self.feedBackBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(188, 188, 188);")
        self.feedBackBrowser.setObjectName("feedBackBrowser")
        self.verticalLayout_4.addWidget(self.feedBackBrowser)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.cortana = QtWidgets.QPushButton(self.page)
        self.cortana.setMinimumSize(QtCore.QSize(152, 177))
        self.cortana.setMaximumSize(QtCore.QSize(152, 177))
        self.cortana.setText("")
        self.cortana.setIconSize(QtCore.QSize(152, 177))
        self.cortana.setFlat(False)
        self.cortana.setObjectName("cortana")
        self.horizontalLayout_2.addWidget(self.cortana)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 354, 491))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.webBrowser = QtWidgets.QTextBrowser(self.widget)
        self.webBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px\n"
"")
        self.webBrowser.setObjectName("webBrowser")
        self.verticalLayout_5.addWidget(self.webBrowser)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.littleCortana = QtWidgets.QPushButton(self.widget)
        self.littleCortana.setMinimumSize(QtCore.QSize(76, 88))
        self.littleCortana.setMaximumSize(QtCore.QSize(76, 88))
        self.littleCortana.setText("")
        self.littleCortana.setIconSize(QtCore.QSize(76, 88))
        self.littleCortana.setObjectName("littleCortana")
        self.horizontalLayout_5.addWidget(self.littleCortana)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.toolBox.addItem(self.widget, "")
        self.gridLayout.addWidget(self.toolBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lightLabel.setText(_translate("MainWindow", "灯"))
        self.lightRadioButton.setText(_translate("MainWindow", "TextLabel"))
        self.doorLable.setText(_translate("MainWindow", "门"))
        self.doorRadioButton.setText(_translate("MainWindow", "TextLabel"))
        self.airConditionerLable.setText(_translate("MainWindow", "空调"))
        self.airConditionerRadioButton.setText(_translate("MainWindow", "TextLabel"))
        self.feedBackBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

import icon_rc
